### ISSUE TITLE
File remains open when project is closed

### ISSUE THREAD

**Issue by ghost** [rochus-keller/LeanCreator#6]
Project open; behaves as expected.

![image](https://user-images.githubusercontent.com/1777466/226126720-dedcaf15-6e47-40c6-8040-36008b34c280.png)

Project closed, file remains open.

![image](https://user-images.githubusercontent.com/1777466/226126744-556bbb64-f5c0-4575-a205-c2a8e0abcbe2.png)

Is this the expected behavior?

**Comment by rochus-keller** [comment]
Qt Creator does the same, so I assume it's intended.

**Comment by stefanos82** [comment]
Let me check my settings.

**Comment by stefanos82** [comment]
Seems like Qt Creator added the following:

![image](https://user-images.githubusercontent.com/1777466/226136130-67b42fc1-55d6-4850-86f5-e5e67d534ac2.png)

**Comment by rochus-keller** [comment]
What Qt Creator version is this? LeanCreator is based on Qt Creator 3.6.1.

**Comment by stefanos82** [comment]
Qt Creator 9.0.2 but I have been using it since...I don't remember exactly which version was the first one I originally installed, but had it there for me.

**Comment by rochus-keller** [comment]
I never really switched to newer versions; on Mac I have version 4.x, but it's slower and has a different ui concept; LeanCreator follows the 3.x philosophy.

**Comment by stefanos82** [comment]
Nice. I guess you meant Qt Creator 3.x and not Qt itself?

**Comment by rochus-keller** [comment]
LeanQt itself is based on Qt 5.6.

**Comment by stefanos82** [comment]
Ah I see, very nice.

By the way, why does it feel like Windows when I hover on the app? The mouse changes to white and brings memories from Wine apps.

**Comment by rochus-keller** [comment]
> why does it feel like Windows when I hover on the app?

Not sure what you mean. The mouse cursor changes shape depending on the context; that's common behaviour in Qt.

**Comment by stefanos82** [comment]
This is in Qt Creator:

![image](https://user-images.githubusercontent.com/1777466/226171722-211011d3-f2a7-4e78-b6f9-b36fd3ce0501.png)

As you can see, my mouse looks the same as my system.

And this is in Lean Creator:

![image](https://user-images.githubusercontent.com/1777466/226171770-74d14092-c5df-47c1-bafa-0c16623c4308.png)

**Comment by rochus-keller** [comment]
I think what you see is just the XOR of the mouse pointer icon with the background which looks different on a dark than on a white background.

**Comment by stefanos82** [comment]
Is it something that comes bundled with LeanQt? I don't have such mouse theme installed to be honest with you.

**Comment by rochus-keller** [comment]
This is generally a feature of the window system in place (X11, Win32, etc.); Qt just provides the bitmap to be displayed at the cursor position.

**Comment by stefanos82** [comment]
Ah yes, now that you mentioned X11 I remember this layout in the past when I was having fun with FreeBSD, back in 2004!

I'm getting old `-_-` !

**Comment by rochus-keller** [comment]
## Summary & Conclusion: 

this is an option available in more recent versions of Qt Creator which I don't thinks is necessary for LeanCreator.
