### ISSUE TITLE
How to change CXX flag in BUSY file to use C++20?

### ISSUE THREAD

**Issue by stefanos82** [rochus-keller/LeanCreator#7]
I created a `BUSY Hello World` demo and tested it; works as expected.

When I try to use a header file, such as `<compare>` it cannot suggest it nor does find anything related to it in `std::` after I add the header.

If I go in `Inspect C++ Code Model`, I can see the following:

![image](https://user-images.githubusercontent.com/1777466/226454439-94e03992-ae72-4be6-ba25-0c890d8ccd91.png)

How can I change it to use `-std=c++20` and other flags I would like to enable?

**Comment by rochus-keller** [comment]
The include paths of the standard library of the compiler in use should actually be in the path; otherwise e.g. LeanQt which makes use of standard library features would not compile; did you have to add the compiler manually or was it auto-detected?

I will try in the Debian 11 image later tonight

**Comment by stefanos82** [comment]
My default BUSY that got generated with demo is the following:

```
let config : Config {
    if (target_os == `linux) || (target_os == `macos) {
        .lib_names += [ "m" "stdc++" ]
        .ldflags += "-shared-libgcc"
    }else if target_os == `win32 {
        .lib_names = [ "Gdi32" "User32" "Shell32" "Comdlg32" ]
    }else {
        error("target os not supported")
    }
}

let hello ! : Executable {
    .sources += ./main.cpp
    .configs += config
}
```

So where exactly in here to place it?

If I place it below `.configs`, it complains.

**Comment by stefanos82** [comment]
Now I need to make it parse included header files that deal with `std`, such as `<compare>` and other standard libraries I may use.

**Comment by rochus-keller** [comment]
> If I place it below .configs, it complains.

If you add a line ".cflags_cc += ... " below ".configs += config", you have to end the latter with a semicolon, otherwise the parser sees ".configs += config.cflags_cc" and complains that the type doesn't have such a field.

> I placed it below .ldflags inside

That's reasonable.

> Now I need to make it parse included header files that deal with std,

The compiler should know where the standard inlude files are; do you get compiler errors? Also don't mix up the toolchain compiler with the internal C++ parser used by LeanCreator to index the source files; until I updated the version of this parser (which is not a high priority for me) don't expect it to recognice syntax later than C++14.

**Comment by stefanos82** [comment]
> If you add a line ".cflags_cc += ... " below ".configs += config", you have to end the latter with a semicolon, otherwise the parser sees ".configs += config.cflags_cc" and complains that the type doesn't have such a field.
>

Done. Now it works fine.
> 
> The compiler should know where the standard inlude files are; do you get compiler errors? Also don't mix up the toolchain compiler with the internal C++ parser used by LeanCreator to index the source files; until I updated the version of this parser (which is not a high priority for me) don't expect it to recognice syntax later than C++14.

I didn't do anything with that; all I did was to open the Inspector window I shared as screenshot above and after I re-opened LeanCreator, it parsed it.

I guess it was doing some parsing in the background while I was writing the initial ticket and did not notice it.

It would be convenient to have `clangd` enabled; that could solve my headaches.

**Comment by stefanos82** [comment]
Ah I misread your answer my apologies.

What I meant with my answer above is that initially the `<compare>` header was unable to be found by the auto-load mechanism (parser?) and after I inserted it manually, I expected it to load its contents in `std` namespace; well, it didn't :disappointed:

**Comment by rochus-keller** [comment]
Ok, I see; I don't feed the include paths of the selected toolchain to the indexer yet (see BusyProject::updateCppCodeModel()); maybe I could do that.

**Comment by stefanos82** [comment]
Can you transfer this issue to Discussions?

**Comment by rochus-keller** [comment]
Not sure whether this can be done; and it's acutally a kind of feature request, so it makes sense to have it in the issues.

**Comment by stefanos82** [comment]
It can be done, there's an option to transfer it in Discussions but as you have said, it makes sense to have it here.
